import Head from "next/head"
import { connect } from "react-redux"
import Feed from "../components/Feed"
import Layout from "../layouts/Layout"

const Home = () => {
  return (
    <Layout>
      <div className="">
        <Head>
          <title>Instagram</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Feed />
      </div>
    </Layout>
  )
}

export default connect((state) => state)(Home)
