import Head from "next/head"
import Feed from "../components/Feed"
import Layout from "../layouts/Layout"

export default function Home() {
  return (
    <Layout>
      <div className="">
        <Head>
          <title>Instagram</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Feed />
      </div>
    </Layout>
  )
}
